argonnepnr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from tourism.admin_contrib import user_admin_site

urlpatterns = [
    path('', include('tourism.urls')),
    path('admin/', admin.site.urls),
    path('contrib/', user_admin_site.urls),
    path('_nested_admin/', include('nested_admin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourism/urls.py
from django.urls import path

from . import views

app_name = 'tourism'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('get/ajax/poi', views.detail, name='poi_detail'),
    path('get/ajax/lazy', views.visible_poi, name='poi_load'),
    path('get/ajax/best', views.best_poi, name='best_results_load'),
    path('communes', views.CommuneView.as_view(), name='commune'),
    path('get/admin/subcategory', views.admin_get_subcategory, name='admin_get_subcategory'),
]

tourism/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.contrib.gis.db import models
from django.contrib.gis.geos import GEOSGeometry

import datetime
from decimal import Decimal
# from django.utils.translation import gettext_lazy as _


class Variable(models.Model):
    name = models.CharField(max_length=20, unique=True, editable=False)
    value = models.FloatField()

    def __str__(self):
        return f"{self.name}={self.value}"


class Category(models.Model):
    name = models.CharField(max_length=150)
    tag = models.CharField(max_length=100, unique=True)
    order = models.IntegerField("ordre", default=100)

    light_color = models.CharField(max_length=7, default="#d54363")
    dark_color = models.CharField(max_length=7, default="#a1334b")

    class Meta:
        verbose_name = "categorie"
        verbose_name_plural = "categories"

    def __str__(self):
        return f"{self.name}"

def get_default_category():
    cat, created = Category.objects.get_or_create(tag="default", defaults={'order': 100})
    cat.icon = "grey"
    if not cat.name:
        cat.name = "(pas de catégorie)"
    cat.save()
    return cat.id


def icon_directory_path(instance, filename):
    return f"icon/{instance.category.tag}/{filename}"

class SubCategory(models.Model):
    name = models.CharField(max_length=150)
    icon = models.FileField(upload_to=icon_directory_path, verbose_name="icône")
    order = models.PositiveIntegerField("ordre")
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        default=get_default_category
    )

    class Meta:
        verbose_name="sous-catégorie"
        verbose_name_plural="sous-catégories"

    def __str__(self):
        return f"{self.name}"


# == Commune ==
class Commune(models.Model):
    name = models.CharField("nom", max_length=50)
    geom = models.MultiPolygonField("géométrie", null=True)
    insee = models.CharField(max_length=5, unique=True)
    postal_code = models.CharField(max_length=5)
    in_argonne_pnr = models.BooleanField("fait partie du PNR ?")

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f"{self.name}"

# == POIs ==
class Place(models.Model):
    name = models.CharField("nom", max_length=100)
    description = models.TextField(blank=True)
    published = models.BooleanField("est publié", default=True)


    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        default=get_default_category
    )
    subcategory = models.ForeignKey(
        SubCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    is_always_open = models.BooleanField("est en permanence ouvert", default=False, null=False, blank=False)

    def save(self, *args, **kwargs):
        ## Check that the selected subcategory belongs to the poi's category
        if self.subcategory and self.subcategory.category.pk != self.category.pk:
            self.subcategory = None
        super().save(*args, **kwargs)


class PointOfInterest(Place):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL
    )
    note_of_interest = models.PositiveSmallIntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
        ]
    )

    location = models.PointField("localication")
    street_address = models.CharField("adresse", max_length=100, blank=True)
    commune = models.ForeignKey(
        Commune,
        on_delete=models.PROTECT,
    )
    
    dt_id = models.CharField(max_length=200)
    dt_categories = models.TextField(max_length=300)
    email = models.EmailField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(max_length=200, blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = "point d'interêt"
        verbose_name_plural = "points d'interêt"

    def __str__(self):
        return f"{self.name} ({self.commune.name})"

class Tour(PointOfInterest):
    path = models.MultiLineStringField("parcours", null=True)
    distance = models.DecimalField("distance", max_digits=6, decimal_places=2, null=True) # km
    time = models.PositiveIntegerField("durée", null=True, blank=True) # min
    uphill = models.PositiveIntegerField("dénivelé positif", null=True, blank=True) # m
    downhill = models.PositiveIntegerField("dénivelé négatif", null=True, blank=True) # m
    elevation_min = models.PositiveIntegerField("altitude maximale", null=True, blank=True) # m
    elevation_max = models.PositiveIntegerField("altitude minimale", null=True, blank=True) # m
    is_closed = models.BooleanField("est une boucle", default=True)

    def compute_length(self):
        if self.path:
            length_m = self.path.transform(3035, clone=True).length  # change coordinates system
            length_km = round(length_m / 1000, 2)
            return Decimal(length_km)

    def get_is_closed(self, thresh=75):
        if self.path:
            if self.path.closed:
                return True
            else:
                p_start = GEOSGeometry("SRID=4326;POINT({} {})".format(*self.path[0][0]))
                p_end = GEOSGeometry("SRID=4326;POINT({} {})".format(*self.path[-1][-1]))
                p_start.transform(3035)
                p_end.transform(3035)
                return p_start.distance(p_end) <= thresh
        

    def save(self, *args, **kwargs):
        cat, created = Category.objects.get_or_create(tag="tour", defaults={'order': 100})
        self.category = cat
        if not self.distance and self.path:
            self.distance = self.compute_length()
        super().save(*args, **kwargs)


    class Meta:
        verbose_name = "randonnée"
        verbose_name_plural = "randonnées"

class Event():
    pass


class ZoneOfInterest(Place):
    zone = models.MultiPolygonField("zone")

    class Meta:
        ordering = ('name',)
        verbose_name = "zone d'interêt"
        verbose_name_plural = "zones d'interêt"


# == Management of opening hours ==
def get_valid_through_default():
        return datetime.date(datetime.date.today().year, 12, 31)

class OpeningPeriod(models.Model):
    """ Opening period """
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    valid_from = models.DateField("valable à partir du", default=datetime.date.today)
    valid_through= models.DateField("valable jusqu'au", blank=True, default=get_valid_through_default)


    class Meta:
        verbose_name = "période d'ouverture"
        verbose_name_plural = "périodes d'ouverture"
        ordering = ['valid_from', 'valid_through']

    def __str__(self):
        return f"{self.place.name} ({self.valid_from} - {self.valid_through}"



class OpeningHours(models.Model):
    """ Typical week's opening hours during a certain opening period (schema) """
    WEEKDAYS = [
        (1, "Lundi"),
        (2, "Mardi"),
        (3, "Mercredi"),
        (4, "Jeudi"),
        (5, "Vendredi"),
        (6, "Samedi"),
        (7, "Dimanche"),
    ]

    schema = models.ForeignKey(OpeningPeriod, on_delete=models.CASCADE)
    weekday = models.PositiveSmallIntegerField("jour de la semaine", choices=WEEKDAYS)
    from_hour = models.TimeField("heure d'ouverture", null=True)
    to_hour = models.TimeField("heure de fermeture", null=True)

    class Meta:
        verbose_name = "horaires d'ouverture"
        verbose_name_plural = "horaires d'ouverture"
        ordering = ['weekday', 'from_hour']

    def __str__(self):
        return f"{self.schema.place.name} {self.weekday} ({self.from_hour} - {self.to_hour})"

# == Media ==
class Media(models.Model):
    title = models.CharField("légende", max_length=150, null=True, blank=True)
    credits = models.CharField("crédits", max_length=100, null=True, blank=True)
    picture = models.ImageField()

    class Meta:
        abstract = True
        

def poi_directory_path(instance, filename):
    return f"poi_{instance.poi.id}/{filename}"

class MainRepresentation(Media):
    picture = models.ImageField(upload_to=poi_directory_path, verbose_name="image principale")
    poi = models.OneToOneField(
        PointOfInterest,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    class Meta:
        verbose_name = "image principale"
        verbose_name_plural = "images principales"

tourism/views.py
from django.core import serializers
from django.http import JsonResponse, HttpResponse, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView

from django.contrib.gis.geos import Polygon
from django.contrib.gis.db import models
from django.db.models import Case, Count, Exists, F, OuterRef, Value, When


from .models import Category, Commune, OpeningPeriod, OpeningHours, PointOfInterest, SubCategory, Variable
from . import utils

import datetime
import json

class IndexView(ListView):
    template_name = 'tourism/index.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        return Category.objects.order_by('order')

# def detail(request):
#     # return JsonResponse({"error": False}, status=200)
#     if request.is_ajax and request.method == "GET":
#         poi_id = request.GET.get("poi_id", None)
#         try:
#             poi = get_object_or_404(PointOfInterest, pk=poi_id)
#             poi_json = serializers.serialize('json', [poi, ])
#             return JsonResponse({"instance": poi_json}, status=200)
#         except PointOfInterest.DoesNotExist:
#             return JsonResponse({}, status=400)
#     return JsonResponse({}, status=400)

def ajax_get_view(view_function):
    def wrapper(request):
        if request.is_ajax and request.method == "GET":
            return view_function(request)
        else:
            return HttpResponseNotAllowed(('GET',))
    return wrapper

@ajax_get_view
def admin_get_subcategory(request):
    id = request.GET.get('id', '')
    subcategories = SubCategory.objects.filter(
        category_id=int(id)
        ).values('id', 'name')
    return JsonResponse({"subcategories": list(subcategories)}, status=200)
    # return HttpResponse(json.dumps(result), content_type="application/json")


@ajax_get_view
def detail(request):
    poi_id = request.GET.get("poi_id", None)
    poi = get_object_or_404(PointOfInterest, pk=poi_id)

    if date_start_str := request.GET.get("date-from", None):
        date_start = datetime.datetime.strptime(date_start_str, '%Y-%m-%d').date()
        date_end = datetime.datetime.strptime(
            request.GET.get("date-to", "9999-12-31"), '%Y-%m-%d'
        ).date()
        opening_schema = OpeningPeriod.objects.filter(
            place=poi,
            valid_from__lte=date_end,
            valid_through__gte=date_start,
            # openingperiod__openinghours__weekday__in = utils.get_isoweekdays_btw_dates(date_start, date_end),
        ).first()
        content = {
            'poi': poi,
            'requested_opening_schema': opening_schema
        }

    else: # get current opening_schema
        opening_schema = OpeningPeriod.objects.filter(
            place=poi,
            valid_from__lte=datetime.date.today(),
            valid_through__gte=datetime.date.today()).first()
        content = {
            'poi': poi,
            'current_opening_schema': opening_schema
        }
    return render(request, 'tourism/index/_detail.html', content)

@ajax_get_view
def visible_poi(request):
    DAYS_XN = Variable.objects.get_or_create(name="XN", defaults={'value':10})[0].value
    DAYS_XP = Variable.objects.get_or_create(name="XP", defaults={'value':3})[0].value
    # Retrieve data
    categories = json.loads(request.GET.get("categories", None))
    name = json.loads(request.GET.get("name", None))

    # Retrieve dates
    date_start = datetime.datetime.strptime(
        request.GET.get("date-from", "2000-1-1"),
        '%Y-%m-%d'
    ).date()
    date_end = datetime.datetime.strptime(
        request.GET.get("date-to", "3000-12-31"),
        '%Y-%m-%d'
    ).date()

    if date_end < date_start:
        return render(
            request,
            'tourism/index/_poi_loader.html',
            {"error": f"La date de fin doit être supérieure à {date_start}."}
        )
    # Retrieve bounds
    # bounds = request.GET.get("bounds", None)
    # bounds_old = request.GET.get("boundsOld", None)  # not set if no move
    # geom_new = utils.to_geom(bounds)  # current zone (after zoom/drag)
    # geom_old = utils.to_geom(bounds_old)  # previous zone (bedore zoom/drag)
    # geom = geom_new - geom_old # new POis are inside this geometry

    # Query
    date_end_later = date_end + datetime.timedelta(days=DAYS_XN)  # XN
    date_end_near = date_end + datetime.timedelta(days=DAYS_XP)  # XP
    openingperiod_later = OpeningPeriod.objects.filter(
        place=OuterRef('pk'),
        valid_from__lte=date_end_later,
        valid_through__gte=date_start,
        openinghours__weekday__in=utils.get_isoweekdays_btw_dates(date_start, date_end_later),
    )
    openingperiod_near = openingperiod_later.filter(
        valid_from__lte=date_end_near,
        openinghours__weekday__in=utils.get_isoweekdays_btw_dates(date_start, date_end_near),
    )
    openingperiod_now = openingperiod_near.filter(
        valid_from__lte=date_end,
        openinghours__weekday__in=utils.get_isoweekdays_btw_dates(date_start, date_end),
    )
    
    poi_list = PointOfInterest.objects.filter(
        # location__within=geom_new,
        category__tag__in=categories,
    ).annotate(
        num_opening_periods=Count('openingperiod'),
        opening_score=Case(
            When(is_always_open=True, then=Value(2)),
            When(Exists(openingperiod_now), then=Value(5)),
            When(Exists(openingperiod_near), then=Value(4)),
            When(Exists(openingperiod_later), then=Value(3)),
            When(num_opening_periods__gt=0, then=Value(1)),
            default=Value(0),
            output_field=models.PositiveSmallIntegerField(),
        ),
        # score=F('opening_score') + F('note_of_interest'),
    )

    if name:
        poi_by_commune_name = poi_list.filter(commune__name__icontains = name)
        poi_by_name = poi_list.filter(name__icontains = name)
        poi_list = poi_by_commune_name.union(poi_by_name)

    content = {
        'poi_list': poi_list.order_by('-opening_score'),
    }
    return render(request, 'tourism/index/_poi_loader.html', content)

@ajax_get_view
def best_poi(request):
    NI_P = Variable.objects.get_or_create(name="P", defaults={'value':3/5})[0].value
    POI_BY_PAGE = 10
    ids = json.loads(request.GET.get("ids", "[]"))
    whens = [When(pk=id, then=opening_score) for id, opening_score in ids.items()]
    page = int(request.GET.get("page", 0))

    # best_results = PointOfInterest.objects.filter(pk__in = ids).order_by('name')[page*POI_BY_PAGE : (page+1)*POI_BY_PAGE]
    best_results = PointOfInterest.objects.filter(pk__in=ids.keys()).annotate(
        opening_score=Case(
            *whens,
            default=0,
            output_field=models.PositiveSmallIntegerField(),
        ),
        score= 2 * NI_P * F('note_of_interest') + 2 * (1 - NI_P) * F('opening_score'),
    ).order_by('-score')[page*POI_BY_PAGE : (page+1)*POI_BY_PAGE]

    content = {
        'poi_list': best_results,
        # 'debug': ids
    }
    return render(request, 'tourism/index/_best_results.html', content)

# == DEBUG COMMUNE ==
class CommuneView(ListView):
    template_name = 'tourism/commune.html'
    context_object_name = 'commune_list'

    def get_queryset(self):
        return Commune.objects.all()

tourism/templates/tourism/index/_best_results.html
{% load openinghours_tags %}

{% if debug %} <span> {{ debug }} </span> {% endif %}
{% for poi in poi_list %}
    {% comment %} {{ poi | is_open:"2020"}} {% endcomment %}
    <article class="card" onmouseover="onResultHover({{poi.id}})" onmouseleave="resetSelectedMarker()" onclick="onResultClick(this, {{poi.id}})">
        <header class="thumb">
        {% if poi.mainrepresentation %}
            {% comment %} <header class="thumb" style="background-image: url('{{ poi.mainrepresentation.picture.url }}')"></header> {% endcomment %}
            <img src="{{ poi.mainrepresentation.picture.url }}" alt="{{ poi.mainrepresentation.picture.title }}" draggable="false">
        {% else %}
            
        {% endif %}
        </header>
        <div class="body">
            <h2 class="title"> {{ poi.name }}</h2>
            <div class="subtitle">
                <span class="city">{{ poi.commune.name }}</span>
                {% if user.is_authenticated %}
                <span class="tag">NI {{ poi.note_of_interest }}</span>
                <span class="tag">NC {{ poi.opening_score }}</span>
                <span class="tag tag-red"> {{ poi.score }}</span>
                {% endif %}
                {% comment %} <span>
                    {% if poi.open %} Ouvert {% else %} Fermé {% endif %}
                    {{ poi.open }}
                </span> {% endcomment %}
            </div>
            <p>{{ poi.description }}</p>
            <div class="rect"></div>
            <div class="rect_white"></div>
        </div>
    </article>
{% endfor %}

<script>
    if ("{{ poi_list.count }}" < 10) {
        $("#show-more").hide();
    } else {
        $("#show-more").show();
    }
</script>

tourism/templates/tourism/index/_date.html
<div id="other-filters">
    <div id="name-filter">
        <label for="name-searchbar"><img src="/static/admin/img/search.svg" alt="Search"></label>
        <input type="text" size="40" name="q" value="" id="name-searchbar" autofocus="" autocomplete="off" onkeydown="onInputKeyDown(event)">
        <div class="btn btn-primary" onclick="onFilterChange()">Valider</div>
    </div>
    <div id="date-filter">
        <label for="start">du :</label>
        <input id="start" type="date" value={% now "Y-m-d" %} onchange="onDateChange()">
        <label for="end">au :</label>
        <input id="end" type="date" onchange="onDateChange()">
    </div>
    <div id="unmodifiable-content">
    </div>
</div>

tourism/templates/tourism/index/_detail.html
{% load tour_tags %}

{% comment %} <div id='site-description'><h1>Hello world from detail.html</h1></div> {% endcomment %}
<h1 class="poi-name"> {{ poi.name |upper }} </h1>

{% if poi.category.tag != 'default' %}
    <span class="tag poi-category"> {{ poi.category.name }}</span>
{% endif %}

{% if user.is_authenticated %}
    <span class="tag poi-id"><a href={{ poi.dt_id}}> {{ poi.id }}</a></span>
    <span class="tag tag-red"><a href="{% url 'admin:tourism_pointofinterest_change' poi.id%}">admin</a></span>

    <p> {{ poi.dt_categories }} </p>
    {% if poi.mainrepresentation %}
    <div class="main-illustration">
        <img src="{{ poi.mainrepresentation.picture.url }}" alt="{{ poi.mainrepresentation.picture.title }}" draggable="false">
        {% if poi.mainrepresentation.credits %}
        <span class="credits"> {{ poi.mainrepresentation.credits }} </span>
        {% endif %}
    </div>
    {% endif %}
{% endif %}

{% if poi.tour %}
<span class="tag tag-brown"> {{ poi.tour.distance }} km</span>
    {% if poi.tour.time %}
    <span class="tag tag-blue"> {{ poi.tour.time|to_hours }} </span>
    {% endif %}
{% endif %}

<div class="description">
    {{ poi.description|linebreaks }}
</div>

<p class="address"> 
    <span class="address-street"> {{ poi.street_address }} </span>
    <span class="address-city"> {{ poi.commune.name }} </span>
</p>

{% if poi.email or poi.phone or poi.website %}
<p class="contact"> 
    <span class="contact-eamil"> {{ poi.email }} </span>
    <span class="contact-phone"> {{ poi.phone }} </span>
    <span class="contact-website"> {{ poi.website }} </span>
</p>
{% endif %}

{% now "l" as current_year %}
{% if current_opening_schema %}
<div class="opening-schema">
    <p> jusqu'au {{ current_opening_schema.valid_through }} </p>
    
    <table>
    {% for day in current_opening_schema.openinghours_set.all %}
        <tr {% if current_year == day.get_weekday_display|lower %} class="today" {% endif %}>
        {% if day.from_hour %}
            <td> {{ day.get_weekday_display }} </td>
            <td> {{ day.from_hour }} - {{ day.to_hour }} </td>
        {% else %}
            <td> {{ day.get_weekday_display }}</td>
        {% endif %}
        </tr>
    {% endfor %}
    </table>
</div>
{% endif %}
{% if requested_opening_schema %}
<div class="opening-schema">
    <p> du {{ requested_opening_schema.valid_from }} au {{ requested_opening_schema.valid_through }} </p>
    
    <table>
    {% for day in requested_opening_schema.openinghours_set.all %}
        <tr>
        {% if day.from_hour %}
            <td> {{ day.get_weekday_display }} </td>
            <td> {{ day.from_hour }} - {{ day.to_hour }} </td>
        {% else %}
            <td> {{ day.get_weekday_display }}</td>
        {% endif %}
        </tr>
    {% endfor %}
    </table>
</div>
{% endif %}

{% comment %} DEBUG {% endcomment %}
{% if user.is_authenticated %}

{% for schema in poi.openingperiod_set.all %}
    <div class="debug" style="color:lightgrey; margin-top:15px">
        <span> du {{ schema.valid_from }} au {{ schema.valid_through }} </span>
        {% for day in schema.openinghours_set.all %}
            {% if day.from_hour %}
                <span> {{ day.get_weekday_display }} de {{ day.from_hour }} à {{ day.to_hour }}</span>
            {% else %}
                <span> {{ day.get_weekday_display }}</span>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

{% endif %}

tourism/templates/tourism/index/_poi_loader.html
{% load l10n %}

{% if error %}
<p class="tag"> {{ error }}</p>
{% else %}

{% comment %} {% if poi_list %} {% endcomment %}
<h1 id="results-title">{{ poi_list.count }} Résultat{{ poi_list.count|pluralize}} </h1>
{% comment %} {% endif %} {% endcomment %}
{% comment %} {% include "tourism/index/_date.html" %}   {% endcomment %}

<div class="debug">
    {% if debug %} <h4> {{ debug }} </h4> {% endif %}
</div>

<div class="results">
    {% comment %} {% include "tourism/index/_best_results.html" %} {% endcomment %}
</div>
<div id="show-more" class="show-more" onclick="loadBestResults(true)"></div>


<script>
{% localize off %}

    var markersLoadedNew = Object(); // key: id -> value: leaflet_id
    var icon;
    // Add all new markers
    {% for poi in poi_list %}
        var poi_id = "{{ poi.id }}";
        if (markersLoaded[poi_id] == null) { // new marker to display
            var lon = "{{ poi.location.x }}";
            var lat = "{{ poi.location.y }}";
            {% if poi.opening_score >= 3 %}
                icon = getIcon("{{ poi.category.tag }}", "{{ poi.category.light_color }}", "{{ poi.category.dark_color }}");
            {% else %}
                icon = getSmallIcon("{{ poi.category.tag }}", "{{ poi.category.dark_color }}");
            {% endif %}
            var marker = L.marker([lat, lon], {
                icon: icon
            });
            marker.on('click', onMarkerClick);
            marker['data-id'] = poi_id;
            marker['data-opening-score'] = "{{ poi.opening_score }}";
            mainLayer.addLayer(marker);
            // markersLayers["{{ poi.category.tag }}"].addLayer(marker);
            markersLoadedNew[poi_id] = marker._leaflet_id;
            
            if ("{{ poi.tour }}") { // TOUR : display path
                var tour_path = '{{ poi.tour.path.json | safe }}';
                var tour_path_geo = L.geoJSON(JSON.parse(tour_path), {
                    style: {
                        color: "#a05a2c",
                        opacity: 0.7,
                    },
                    bubblingMouseEvents: false, // prevent click on map to be triggered
                });
                tour_path_geo.on('click', onTourClick);
                tour_path_geo.addTo(map);

                // Bind path with its marker
                tour_path_geo['data-marker'] = marker;
                marker['data-tour'] = tour_path_geo;
            }
        } else {
            markersLoadedNew[poi_id] = markersLoaded[poi_id]
        }
    {% endfor %}

    // console.log("markersLoaded New", markersLoadedNew);


    // Remove unwanted markers (not in leagletIdToKeep)
    leafletIdToKeep = Object.values(markersLoadedNew);
    // console.log("leafletIdToKeep", leafletIdToKeep);

    mainLayer.eachLayer(function (marker) {
        if (!(leafletIdToKeep.includes(marker._leaflet_id))) {
            mainLayer.removeLayer(marker);
            if (marker['data-tour']) { // If TOUR
                map.removeLayer(marker['data-tour']);
            }
        }
    });

    var i = markersHidden.length;
    while (i--) {
        marker = markersHidden[i];
        if (!(leafletIdToKeep.includes(marker._leaflet_id))) {
            markersHidden.splice(i, 1);
        }
    }

    markersLoaded = markersLoadedNew;
    showMarkersInBounds();
    loadBestResults();

{% endlocalize %}
</script>
{% endif %}